spring.application.name=projeto_individual_fisio4life

spring.datasource.url=jdbc:h2:mem:fisio4life_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Habilitar o console H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

